frendo:
    generator:
        userAmount: 1000
        extraText: classpath:chamber-of-secrets.txt
    cache.retryTimeoutMillis: 10000

spring:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
    datasource:
        url: jdbc:h2:./frendo
        driverClassName: org.h2.Driver
        username: sa
        password:
    h2.console.enabled: true
