frendo.generator.userAmount: 1000
frendo.cache.retryTimeoutMillis: 10000

spring.jpa.properties:
    hibernate.cache.use_second_level_cache: false
    hibernate.cache.use_query_cache: false

spring.datasource:
    url: jdbc:h2:./frendo
    driverClassName: org.h2.Driver
    username: sa
    password:

spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

spring.h2.console.enabled: true
